// Animates the pink ASCII Hello Kitty in the landing background.
// Frames come from kitty-frames.js (window.KITTY_FRAMES, window.KITTY_FRAME_MS),
// which is generated by tools/gen-ascii.py.
(function () {
  var el = document.getElementById("kitty");
  var frames = window.KITTY_FRAMES;
  if (!el || !frames || !frames.length) return;

  // Always paint the first frame so something shows even if motion is reduced.
  el.innerHTML = frames[0];

  var reduceMotion =
    window.matchMedia && window.matchMedia("(prefers-reduced-motion: reduce)").matches;
  if (reduceMotion || frames.length < 2) return;

  var i = 0;
  var timer = null;
  var interval = window.KITTY_FRAME_MS || 120;

  function tick() {
    i = (i + 1) % frames.length;
    el.innerHTML = frames[i];
  }
  function start() {
    if (!timer) timer = window.setInterval(tick, interval);
  }
  function stop() {
    if (timer) {
      window.clearInterval(timer);
      timer = null;
    }
  }

  // Pause while the tab is hidden to save work.
  document.addEventListener("visibilitychange", function () {
    if (document.hidden) stop();
    else start();
  });

  start();
})();
